### ISSUE TITLE
Feature request: trace id

### ISSUE THREAD

**Issue by atrinchillo-mwb** [signalfx/splunk-extension-wrapper#56]
Is it possible to add the trace id on the output of the wrapper
It is useful if from logs on cloudwatch you want to search a trace by id in signalfx

**Comment by kubawach** [comment]
Correct :) And it's already possible - just add logging exporter to the list of exporter (name of the exporter varies between languages). Closing the issue here - let's discuss in the other repo in case of any further questions.
