### ISSUE TITLE
Strange warnings

### ISSUE THREAD

**Issue by atrinchillo-mwb** [signalfx/splunk-extension-wrapper#57]
After activating the wrapper I have these warning, but it seams that data in reality arrives to signal
Could you please clarify these strange messages?

[splunk-extension-wrapper] can't parse bool: | [splunk-extension-wrapper] can't parse bool:
-- | --

[splunk-extension-wrapper] can't parse number of seconds: nan | [splunk-extension-wrapper] can't parse number of seconds: nan
-- | --

**Comment by kubawach** [comment]
This layer: https://github.com/signalfx/lambda-layer-versions/blob/master/splunk-apm/splunk-apm.md contains both the extension (https://github.com/signalfx/lambda-layer-versions/blob/master/lambda-extension/lambda-extension-versions.md) and set of tracing wrappers. So in general we recommend to follow the official docs and use https://github.com/signalfx/lambda-layer-versions/blob/master/splunk-apm/splunk-apm.md for both metrics and traces :)
